apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy-sa
  namespace: fastfood
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy-binding
subjects:
  - kind: ServiceAccount
    name: alloy-sa
    namespace: fastfood
roleRef:
  kind: ClusterRole
  name: alloy-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-alloy
  namespace: fastfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-alloy
  template:
    metadata:
      labels:
        app: grafana-alloy
    spec:
      serviceAccountName: alloy-sa
      containers:
        - name: alloy
          image: grafana/alloy:latest
          args:
            - "run"
            - "/etc/alloy/config.alloy"
            - "--server.http.listen-addr=0.0.0.0:12345"
          ports:
            - containerPort: 12345
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
            - name: grafana-cloud-secret
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: grafana-cloud-secret
          secret:
            secretName: grafana-cloud-prom
