apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-prom
  namespace: fastfood
type: Opaque
stringData:
  url: https://prometheus-prod-XX-prod-REGION.grafana.net/api/prom/push
  username: "YOUR_GRAFANA_CLOUD_USER_ID"
  password: "YOUR_GRAFANA_CLOUD_API_KEY"
