apiVersion: v1
kind: Service
metadata:
  name: fastfood-api-service
  namespace: fastfood
spec:
  type: NodePort
  selector:
    app: fastfood-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000